name = "ctrl-meteor"
main = "worker.js"
compatibility_date = "2025-10-05"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cosmosim-bucket"

[vars]
NASA_API_KEY = "YOUR_NASA_KEY_HERE"

# Use KV/Assets for static files
type = "javascript"
